name: Deploy Static Website

on:
  push:
    branches:
      - main  # Можно указать другую ветку, если хотите
    paths:
      - '**/*.html'
      - '**/*.css'
      - '**/*.js'
      - '**/*.png'
      - '**/*.jpg'
      - '**/*.svg'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Добавьте приватный ключ SSH в secrets вашего репозитория

      - name: Deploy files to remote server
        run: |
          ssh -o StrictHostKeyChecking=no username@your.server.com "mkdir -p ~/public_html"
          scp -r ./* username@your.server.com:~/public_html/
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

